<a href="https://colab.research.google.com/github/antoreep-jana/YouTube_Code_Repositories/blob/main/Weekly%20Sessions/Weekly_Session_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Reservoir Sampling

In [ ]:
import random

In [ ]:
n = 20

k = 5

input_array = [1,123,32,12,98,12,76, 34, 76, 9, 90, 89, 96, 59, 94, 91, 101, 199, 201, 899 ]

output_array = list()

In [ ]:
for i in range(k):
  output_array.append(input_array[i])



In [ ]:
output_array

[1, 123, 32, 12, 98]

In [ ]:

for j in range(k, n):
  num = random.randint(0, j)

  if num < k:
    output_array[num] = input_array[j]


output_array

[201, 9, 94, 101, 76]

[34, 76, 89, 90, 9]

## UpSampling2D & Conv2DTranspose

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
matrix = np.array([[1,2], [3,4]])

In [ ]:
matrix = matrix.reshape((1,2,2,1))

In [ ]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.UpSampling2D(input_shape = (2,2,1), interpolation='nearest', size = (3,3)))
model.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_11 (UpSampling (None, 6, 6, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [ ]:
yhat = model.predict(matrix)
print(yhat.reshape((6,6)))

[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [3. 3. 3. 4. 4. 4.]
 [3. 3. 3. 4. 4. 4.]
 [3. 3. 3. 4. 4. 4.]]


Conv2DTranspose

In [ ]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2DTranspose(1, (1,1), strides = (2,2), input_shape = (2,2,1)))
model.summary()

Model: "sequential_16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose_3 (Conv2DTr (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [ ]:
matrix.shape

(1, 2, 2, 1)

In [ ]:
model.get_weights()

[array([[[[-0.02408469]]]], dtype=float32), array([0.], dtype=float32)]

In [ ]:
weights = [np.array([[[[2]]]]), np.array([0])]

model.set_weights(weights)

In [ ]:
yhat = model.predict(matrix)

print(yhat.reshape((4,4)))

[[2. 0. 4. 0.]
 [0. 0. 0. 0.]
 [6. 0. 8. 0.]
 [0. 0. 0. 0.]]


# Label Smoothing

In [ ]:
import tensorflow as tf

In [ ]:
import numpy as np
def label_smoother(labels, factor, num_classes):
  new_labels = labels * (1 - factor) + factor/num_classes
  print(new_labels)

In [ ]:

label_smoother(np.array([0, 0 ,1]), 0.3, 3)

[0.1 0.1 0.8]


In [ ]:
y_true = [0, 1, 1]
y_pred = [0.8, 0.99, 0.01]
tf.keras.losses.binary_crossentropy(
    y_true, y_pred,
    from_logits=False,
    label_smoothing=0.1
)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0517778>